# Generated by Django 4.2.5 on 2024-03-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='icColor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
