# Generated by Django 4.2.5 on 2024-03-10 09:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(default='', max_length=200)),
                ('applicant_status', models.CharField(max_length=30)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('source', models.CharField(max_length=200)),
                ('prevApplication', models.CharField(max_length=3, null=True)),
                ('datePrev', models.DateField(null=True)),
                ('postApplied', models.CharField(default='', max_length=20)),
                ('presentEmployment', models.JSONField(null=True)),
                ('academicRec', models.JSONField(null=True)),
                ('membershipFellowship', models.JSONField(null=True)),
                ('experienceHighEd', models.CharField(max_length=3, null=True)),
                ('employmentRecHighEd', models.JSONField(null=True)),
                ('experienceInd', models.CharField(max_length=3, null=True)),
                ('employmentRecInd', models.JSONField(null=True)),
                ('coursesOffering', models.JSONField(null=True)),
                ('teachingSupervision', models.JSONField(null=True)),
                ('languages', models.JSONField(null=True)),
                ('otherLanguages', models.JSONField(null=True)),
                ('family', models.JSONField(null=True)),
                ('referees', models.JSONField(null=True)),
                ('documents', models.JSONField(null=True)),
                ('consent', models.CharField(default='Yes', max_length=3, null=True)),
                ('applicant_progress', models.CharField(default='In Progress', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bookmarked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bookmark', models.CharField(max_length=5, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('color', models.CharField(max_length=255, null=True)),
                ('application_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark', models.JSONField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, null=True)),
                ('icon', models.ImageField(blank=True, upload_to='department-icon/')),
                ('category', models.CharField(max_length=20, null=True)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=40, null=True)),
                ('status', models.CharField(max_length=200)),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('salaryMin', models.IntegerField()),
                ('salaryMax', models.IntegerField()),
                ('minReq', models.CharField(max_length=200)),
                ('yearsExp', models.IntegerField()),
                ('description', models.TextField()),
                ('contractDur', models.IntegerField()),
                ('dateClose', models.DateField()),
                ('jobForm', models.CharField(max_length=200)),
                ('btnMsg', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
