# Generated by Django 4.2.5 on 2024-03-10 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mod.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('myfiles', models.FileField(default='', max_length=1000, upload_to=mod.models.user_directory_path)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod.application')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('change_password', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('member_type', models.CharField(default='', max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod.department')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod.department'),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod.job'),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod.recruiter'),
        ),
        migrations.AddField(
            model_name='bookmarked',
            name='bookmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod.bookmarks'),
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod.job'),
        ),
        migrations.AddField(
            model_name='application',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.applicant'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
