# Generated by Django 4.2.5 on 2024-03-11 10:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarked',
            name='application_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), null=True, size=None),
        ),
    ]
