# Generated by Django 4.2.5 on 2024-03-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0004_application_scholarlyinfo_application_scopusinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expGov',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='expGovInfo',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='header',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(null=True),
        ),
    ]
