# Generated by Django 4.2.5 on 2024-03-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0005_job_expgov_job_expgovinfo_job_header_job_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contractDur',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='yearsExp',
            field=models.IntegerField(null=True),
        ),
    ]
