# Generated by Django 4.2.5 on 2024-03-19 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0006_alter_job_contractdur_alter_job_yearsexp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='coursesOffering',
        ),
        migrations.RemoveField(
            model_name='application',
            name='employmentRecHighEd',
        ),
        migrations.RemoveField(
            model_name='application',
            name='employmentRecInd',
        ),
        migrations.RemoveField(
            model_name='application',
            name='experienceHighEd',
        ),
        migrations.RemoveField(
            model_name='application',
            name='experienceInd',
        ),
        migrations.RemoveField(
            model_name='application',
            name='family',
        ),
        migrations.RemoveField(
            model_name='application',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='application',
            name='membershipFellowship',
        ),
        migrations.RemoveField(
            model_name='application',
            name='otherLanguages',
        ),
        migrations.RemoveField(
            model_name='application',
            name='postApplied',
        ),
        migrations.RemoveField(
            model_name='application',
            name='referees',
        ),
        migrations.RemoveField(
            model_name='application',
            name='scholarlyInfo',
        ),
        migrations.RemoveField(
            model_name='application',
            name='scopusInfo',
        ),
        migrations.RemoveField(
            model_name='application',
            name='teachingSupervision',
        ),
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='AcademicApplication',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('postApplied', models.CharField(default='', max_length=20)),
                ('membershipFellowship', models.JSONField(null=True)),
                ('experienceHighEd', models.CharField(max_length=3, null=True)),
                ('employmentRecHighEd', models.JSONField(null=True)),
                ('experienceInd', models.CharField(max_length=3, null=True)),
                ('employmentRecInd', models.JSONField(null=True)),
                ('coursesOffering', models.JSONField(null=True)),
                ('teachingSupervision', models.JSONField(null=True)),
                ('scholarlyInfo', models.JSONField(null=True)),
                ('scopusInfo', models.JSONField(null=True)),
                ('languages', models.JSONField(null=True)),
                ('otherLanguages', models.JSONField(null=True)),
                ('family', models.JSONField(null=True)),
                ('referees', models.JSONField(null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod.application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
