# Generated by Django 4.2.5 on 2024-03-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0007_remove_application_coursesoffering_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonAcademicApplication',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('drivingLicense', models.CharField(max_length=3, null=True)),
                ('drivingLicenseType', models.CharField(max_length=20, null=True)),
                ('languages', models.JSONField(null=True)),
                ('highestEducationLevel', models.CharField(max_length=50, null=True)),
                ('expGov', models.CharField(max_length=3, null=True)),
                ('workExperience', models.JSONField(null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod.application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
