# Generated by Django 4.2.5 on 2024-03-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0009_alter_application_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_status',
            field=models.CharField(default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='fullname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
