# Generated by Django 4.2.5 on 2024-03-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0010_alter_application_applicant_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='source',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
