# Generated by Django 4.2.5 on 2024-03-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiter', '0001_initial'),
        ('mod', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='justification',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod.recruiter'),
        ),
    ]
