# Generated by Django 4.2.5 on 2024-03-16 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0004_application_scholarlyinfo_application_scopusinfo'),
        ('recruiter', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('seminar_date', models.DateField()),
                ('review_date', models.DateField()),
                ('content_score', models.JSONField(null=True)),
                ('content_remarks', models.TextField(null=True)),
                ('quality_score', models.JSONField(null=True)),
                ('quality_remarks', models.TextField(null=True)),
                ('communication_score', models.JSONField(null=True)),
                ('communication_remarks', models.TextField(null=True)),
                ('overall_score', models.JSONField(null=True)),
                ('overall_remarks', models.TextField(null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod.application')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod.recruiter')),
            ],
        ),
    ]
